version: '3.7'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat-app
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - chat-app-network


volumes:
  postgresql_data:

networks:
  chat-app-network:
    driver: bridge